import type { ThemeRegistration } from "shiki/core";

export const builtinThemes = {
  dark: {
    name: "lilac-dark",
    type: "dark",
    colors: {
      "editor.background": "#17161a",
      "editor.foreground": "#eeeaf1",
      "sideBar.background": "#211f25",
      "sideBar.foreground": "#eeeaf1",
      "editorWidget.background": "#302c38",
      "editorWidget.foreground": "#eeeaf1",
      "input.background": "#211f25",
      "input.foreground": "#eeeaf1",
      "list.hoverBackground": "#2c2932",
      "list.activeSelectionBackground": "#302c38",
      "button.background": "#b79ccf",
      "button.foreground": "#211629",
      "button.hoverBackground": "#cfb8e2",
      "button.secondaryBackground": "#2c2932",
      "button.secondaryForeground": "#eeeaf1",
      "button.secondaryHoverBackground": "#302c38",
      "textLink.foreground": "#b79ccf",
      descriptionForeground: "#aaa2b1",
      focusBorder: "#cfb8e2",
      errorForeground: "#e991a0",
      "testing.iconPassed": "#8ebeae",
      "editorWarning.foreground": "#dfb65a",
      "editorInfo.foreground": "#58a6ff",
      "widget.shadow": "#0006",
    },
  },
  light: {
    name: "lilac-light",
    type: "light",
    colors: {
      "editor.background": "#faf9fb",
      "editor.foreground": "#27212d",
      "sideBar.background": "#efedf2",
      "sideBar.foreground": "#27212d",
      "editorWidget.background": "#ffffff",
      "editorWidget.foreground": "#27212d",
      "input.background": "#efedf2",
      "input.foreground": "#27212d",
      "list.hoverBackground": "#e5e0ea",
      "list.activeSelectionBackground": "#ffffff",
      "button.background": "#705386",
      "button.foreground": "#ffffff",
      "button.hoverBackground": "#754593",
      "button.secondaryBackground": "#e5e0ea",
      "button.secondaryForeground": "#27212d",
      "button.secondaryHoverBackground": "#ffffff",
      "textLink.foreground": "#705386",
      descriptionForeground: "#6e6378",
      focusBorder: "#754593",
      errorForeground: "#b83250",
      "testing.iconPassed": "#346e5a",
      "editorWarning.foreground": "#946900",
      "editorInfo.foreground": "#0969da",
      "widget.shadow": "#30203826",
    },
  },
} satisfies Record<"light" | "dark", ThemeRegistration>;
