export const CORE_FINAL_EXCEPTION_IDENTITIES = [
  [
    "src/conversation/thread-embedding.ts",
    "createConversationThreadEmbeddingAdapterResolver.resolve.catch",
    "signal",
  ],
  ["src/conversation/thread-materializer-worker-isolate.ts", "runRequest.catch", "signal"],
  [
    "src/conversation/thread-materializer-worker.ts",
    "startConversationThreadMaterializer.postRequest.catch",
    "signal",
  ],
  ["src/conversation/thread-materializer.ts", "mapListChannelIdsError", "signal"],
  [
    "src/conversation/thread-materializer.ts",
    "createThreadMaterializer.reportError.catch",
    "signal",
  ],
  ["src/conversation/thread-materializer.ts", "createThreadMaterializer.drain.catch", "signal"],
  ["src/conversation/thread-service.ts", "readPromptContextFile.catch", "signal"],
  ["src/conversation/thread-service.ts", "parseSummaryJson.catch", "signal"],
  ["src/conversation/thread-service.ts", "parseQueryAboutnessJson.catch", "signal"],
  ["src/conversation/thread-service.ts", "parseAutoInjectQueryPlanJson.catch", "signal"],
  ["src/conversation/thread-service.ts", "adaptConversationThreadGenerationResultToHost", "signal"],
  ["src/conversation/thread-service.ts", "defaultSummarizer.catch", "signal"],
  [
    "src/conversation/thread-service.ts",
    "ConversationThreadService.runSummarization.processThread.catch",
    "signal",
  ],
  [
    "src/conversation/thread-service.ts",
    "ConversationThreadService.summarizeWithParseRetries.catch",
    "signal",
  ],
  [
    "src/conversation/thread-service.ts",
    "ConversationThreadService.tryEmbedThread.catch",
    "signal",
  ],
  [
    "src/conversation/thread-service.ts",
    "ConversationThreadService.captureQueryAboutness.catch",
    "signal",
  ],
  ["src/conversation/thread-service.ts", "ConversationThreadService.searchHits.catch", "signal"],
  [
    "src/conversation/thread-store.ts",
    "ConversationThreadStore.loadVectorExtension.catch",
    "signal",
  ],
  ["src/conversation/thread-store.ts", "ConversationThreadStore.attachSurfaceDb.catch", "signal"],
  [
    "src/conversation/thread-store.ts",
    "ConversationThreadStore.hasRequiredSurfaceTables.catch",
    "signal",
  ],
  ["src/github/github-api.ts", "captureGithubResponseText", "both"],
  ["src/github/github-api.ts", "githubFetchJson", "signal"],
  ["src/github/github-api.ts", "githubFetchNoBody", "signal"],
  ["src/github/github-api.ts", "captureGithubAppResponse", "both"],
  ["src/github/github-app-token.ts", "parseExpiresAtMs", "signal"],
  ["src/github/github-app-token.ts", "getGithubInstallationTokenOrThrow", "signal"],
  ["src/github/github-app.ts", "decodeGithubAppSecret", "both"],
  ["src/github/github-app.ts", "chmod0600", "capture"],
  ["src/github/github-app.ts", "readGithubAppSecretResult", "both"],
  ["src/github/github-app.ts", "readGithubAppSecret", "signal"],
  ["src/github/github-app.ts", "clearGithubAppSecret", "capture"],
  ["src/github/github-app.ts", "readGithubAppPrivateKeyPem", "signal"],
  ["src/github/github-auth.ts", "fetchViewerLoginFromGithub", "both"],
  ["src/github/github-auth.ts", "getGithubViewerLoginOrNull", "capture"],
  ["src/github/github-auth.ts", "getPreferredGithubAuthOrThrow", "signal"],
  ["src/github/github-auth.ts", "getGithubEnvForBash", "capture"],
  ["src/github/github-ids.ts", "parseGithubSessionId", "signal"],
  ["src/github/github-user-token.ts", "decodeGithubUserTokenSecret", "both"],
  ["src/github/github-user-token.ts", "chmod0600", "capture"],
  ["src/github/github-user-token.ts", "readGithubUserTokenSecretResult", "both"],
  ["src/github/github-user-token.ts", "readGithubUserTokenSecret", "signal"],
  ["src/github/github-user-token.ts", "writeGithubUserTokenSecret", "signal"],
  ["src/github/github-user-token.ts", "clearGithubUserTokenSecret", "capture"],
  ["src/github/webhook/github-webhook-server.ts", "decodeGithubWebhookEvent", "both"],
  ["src/github/webhook/github-webhook-server.ts", "captureGithubWebhookOperation", "both"],
  ["src/mcp/catalog-identity.ts", "parseCatalogToolStableId", "capture"],
  ["src/mcp/catalog.ts", "buildUnifiedToolCatalog", "signal"],
  ["src/mcp/catalog.ts", "createPortableToolSearch", "signal"],
  ["src/mcp/config-file.ts", "enqueueMutation", "capture"],
  ["src/mcp/config.ts", "validateHttpServerInputV1", "capture"],
  ["src/mcp/config.ts", "toConfigInputV1", "signal"],
  ["src/mcp/config.ts", "parseMcpConfigYaml", "capture"],
  ["src/mcp/credential-file.ts", "resolveMcpOAuthCredentialPath", "signal"],
  ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFileResult", "both"],
  ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFile", "signal"],
  ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomicResult", "capture"],
  ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomicResult.finish", "signal"],
  ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomic", "signal"],
  ["src/mcp/credential-file.ts", "updateMcpOAuthCredentialFileResult", "capture"],
  ["src/mcp/credential-file.ts", "updateMcpOAuthCredentialFile", "signal"],
  ["src/mcp/oauth-callback.ts", "McpOAuthCallbackService.start", "capture"],
  ["src/mcp/oauth-provider.ts", "captureOAuthAttempt", "capture"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProvider.clientInformation", "signal"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProvider.startAuthorization", "signal"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProvider.completeAuthorization", "signal"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProvider.assertActive", "signal"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProvider.rejectImplicitAuthorization", "signal"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProviderService.startAuthorization", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.constructor", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.init.runLifecycle.<callback@1>", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.shutdown.runLifecycle.<callback@1>", "signal"],
  [
    "src/mcp/registry.ts",
    "McpRegistry.shutdown.runLifecycle.<callback@1>.map.<callback@1>",
    "capture",
  ],
  ["src/mcp/registry.ts", "McpRegistry.runLifecycle", "capture"],
  ["src/mcp/registry.ts", "McpRegistry.assertRunning", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.reconcileServer", "both"],
  ["src/mcp/registry.ts", "McpRegistry.initializeCandidate", "capture"],
  ["src/mcp/registry.ts", "McpRegistry.initializeCandidate.withDeadline.<callback@2>", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.listAllTools", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.discoverTools", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute", "both"],
  ["src/mcp/registry.ts", "McpRegistry.handleTerminalFailure", "capture"],
  ["src/mcp/registry.ts", "McpRegistry.closeEntry", "capture"],
  ["src/mcp/registry.ts", "McpRegistry.closeClientOnce", "both"],
  ["src/mcp/registry.ts", "McpRegistry.closeClientInBackground", "capture"],
  ["src/mcp/registry.ts", "McpRegistry.closeTransportOnce", "both"],
  ["src/mcp/registry.ts", "McpRegistry.closeTransportInBackground", "capture"],
  ["src/plugins/builtin/local-tools.ts", "canonicalizeAsFarAsExists", "both"],
  ["src/plugins/builtin/local-tools.ts", "assertLocalApplyPatchPathsAllowed", "both"],
  ["src/plugins/builtin/local-tools.ts", "captureLocalApplyPatchGuard", "both"],
  ["src/plugins/builtin/local-tools.ts", "signalBuiltinToolHostError", "signal"],
  ["src/plugins/builtin/server-tools.ts", "signalBuiltinPluginSkip", "signal"],
  ["src/runtime/core-config-watch.ts", "captureCoreConfigWatchRead", "both"],
  [
    "src/runtime/create-core-runtime.ts",
    "createCoreRuntime.readCoreConfigParserVersion",
    "capture",
  ],
  ["src/runtime/create-core-runtime.ts", "createCoreRuntime.probeRedisHealth", "capture"],
  ["src/runtime/create-core-runtime.ts", "createCoreRuntime.validateCoreConfigOnChange", "capture"],
  ["src/runtime/create-core-runtime.ts", "createCoreRuntime.startCoreConfigWatcher", "capture"],
  ["src/runtime/process-handlers.ts", "createProcessHandlers.handleSignal", "capture"],
  ["src/runtime/process-handlers.ts", "createProcessHandlers.handleFatal", "capture"],
  ["src/surface/adapter.ts", "preserveSurfacePanic", "signal"],
  ["src/surface/bridge/bus-agent-runner.ts", "resolveCoreStableNamedContinuation", "signal"],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "maybeBuildAutoInjectedThreadSearchMessages.publishToolStatusBestEffort",
    "capture",
  ],
  ["src/surface/bridge/bus-agent-runner.ts", "maybeBuildAutoInjectedThreadSearchMessages", "both"],
  ["src/surface/bridge/bus-agent-runner.ts", "maybeBuildSkillsSectionForPrimary", "both"],
  ["src/surface/bridge/bus-agent-runner.ts", "resolveAgentRunModel", "signal"],
  ["src/surface/bridge/bus-agent-runner.ts", "assertWorkflowDispatchPolicy", "signal"],
  ["src/surface/bridge/bus-agent-runner.ts", "applyToRunningAgent.promptWhileIdle", "capture"],
  ["src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts", "runCommand", "capture"],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "renderAnthropicFallbackImageCandidate",
    "capture",
  ],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "fitImageForAnthropicFallback",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "readAnthropicFallbackCache",
    "capture",
  ],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "writeAnthropicFallbackCache",
    "capture",
  ],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "resolveAnthropicFallbackDownload",
    "signal",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
    "createCoreNamedClaudeRuntime.materializeAttempt",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
    "createCoreNamedClaudeRuntime.createCandidate",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
    "createCoreNamedClaudeRuntime.recordSuccessfulModelCall",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
    "createCoreNamedClaudeRuntime.finalize",
    "capture",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
    "createCorePrimaryClaudeRuntime.materializeAttempt",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
    "createCorePrimaryClaudeRuntime.createCandidate",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
    "createCorePrimaryClaudeRuntime.recordSuccessfulModelCall",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
    "createCorePrimaryClaudeRuntime.finalize",
    "capture",
  ],
  ["src/surface/bridge/bus-agent-runner/formatting.ts", "safeStringify", "capture"],
  [
    "src/surface/bridge/bus-agent-runner/output-publisher.ts",
    "adaptAgentOutputPublishResultToHost",
    "signal",
  ],
  [
    "src/surface/bridge/bus-agent-runner/prompt-overlays.ts",
    "resolveSessionAdditionalPrompts",
    "both",
  ],
  [
    "src/surface/bridge/bus-agent-runner/subagent-prompt.ts",
    "buildSystemPromptForProfile",
    "signal",
  ],
  [
    "src/surface/bridge/bus-agent-runner/tool-failure-logging.ts",
    "toSerializablePreview",
    "capture",
  ],
  [
    "src/surface/discord/discord-request-router/common.ts",
    "parseDiscordMsgRefFromAdapterEvent",
    "signal",
  ],
  ["src/surface/discord/discord-request-router/gate.ts", "shouldForwardByGate", "capture"],
  [
    "src/surface/discord/discord-request-router.ts",
    "signalDiscordRequestRouterPlatformMismatch",
    "signal",
  ],
  [
    "src/surface/bridge/discord-search-indexer.ts",
    "startDiscordSearchIndexer.subscribe.<callback@1>",
    "capture",
  ],
  ["src/surface/bridge/publish-to-bus.ts", "bridgeAdapterToBus.subscribe.<callback@1>", "capture"],
  ["src/surface/bridge/request-composition.ts", "composeSelectedDiscordChain", "signal"],
  ["src/surface/bridge/request-composition.ts", "compareDiscordSnowflakeLike", "capture"],
  ["src/surface/bridge/request-composition.ts", "composeRequestMessages", "signal"],
  ["src/surface/bridge/request-composition.ts", "composeRecentChannelMessages", "both"],
  ["src/surface/bridge/request-composition.ts", "composeSingleMessageWithLineage", "signal"],
  ["src/surface/bridge/request-composition/attachments.ts", "downloadDiscordAttachment", "signal"],
  ["src/surface/bridge/request-composition/attachments.ts", "resolveOwnedFileData", "signal"],
  [
    "src/surface/bridge/request-composition/attachments.ts",
    "appendDiscordAttachmentsToUserContent",
    "both",
  ],
  [
    "src/surface/bridge/request-composition/reply-chain.ts",
    "compareDiscordSnowflakeLike",
    "capture",
  ],
  ["src/surface/bridge/surface-metadata.ts", "parseSurfaceMetadataLine", "capture"],
  ["src/surface/discord/discord-actions.ts", "buildDiscordActionCustomId", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.connect", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.disconnect", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.getSelf", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.reloadCoreConfigIfNeeded", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.applyConfiguredPresence", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.burstCache", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchGuildIdForChannel", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.startOutput", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.startTyping", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.startTyping.tick", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.sendMsg", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.readMsg", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.listMsg", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.editMsg", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.deleteMsg", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.getReplyContext", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.planReplyChain", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.planMergeBlockEndingAt", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.addReaction", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.removeReaction", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.listReactions", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.listReactionDetails", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.listSessionParticipants", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchAllReactionUsers", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.getUnRead", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.markRead", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.mustClient", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.mustStore", "signal"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.ensureMessageRelation", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onInteractionCreate", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.registerSlashCommands", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onChatInputCommand", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onAutocomplete", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchDiscordMessage", "both"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchDiscordMessages", "capture"],
  [
    "src/surface/discord/discord-adapter.ts",
    "DiscordAdapter.toSurfaceMessageFromDiscordMessage",
    "signal",
  ],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onMessageCreate", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.isReplyToBot", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onMessageUpdate", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onMessageDelete", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onReactionAdd", "capture"],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.onReactionRemove", "capture"],
  ["src/surface/discord/discord-cancel.ts", "fromBase64Url", "capture"],
  ["src/surface/discord/discord-channel-guards.ts", "resolveTextSendableChannel", "capture"],
  ["src/surface/discord/discord-channel-guards.ts", "tryReplyEphemeral", "capture"],
  ["src/surface/discord/discord-channel-guards.ts", "tryEditOrReplyEphemeral", "capture"],
  ["src/surface/discord/discord-session-model.ts", "resolveDiscordSurfaceEditTarget", "signal"],
  ["src/surface/discord/output/discord-output-stream.ts", "fetchTextChannel", "both"],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "fetchExistingMessagesForResume",
    "capture",
  ],
  ["src/surface/discord/output/discord-output-stream.ts", "safeEdit", "capture"],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.notifyCreated",
    "capture",
  ],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.deleteTransientPreviewMessages",
    "capture",
  ],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.deleteMessageRef",
    "capture",
  ],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.ensureStarted",
    "signal",
  ],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.postFinalReplyEmbeds",
    "signal",
  ],
  [
    "src/surface/discord/output/discord-output-stream.ts",
    "DiscordOutputStream.postFinalReplyPlain",
    "signal",
  ],
  ["src/surface/discord/output/discord-output-stream.ts", "DiscordOutputStream.finish", "both"],
  ["src/surface/discord/output/embed-pusher.ts", "startEmbedPusher", "signal"],
  ["src/surface/store/discord-search-store.ts", "DiscordSearchService.maybeHealChannel", "capture"],
  ["src/tools/restricted-bash.ts", "captureRestrictedHostPromise", "capture"],
  ["src/tools/tool-result-adapters.ts", "preserveToolPanic", "signal"],
  ["src/tools/tool-result-adapters.ts", "adaptToolResultToHost", "signal"],
  ["src/transcript/heartbeat-handoff.ts", "safeStringify.catch", "signal"],
  ["src/workflow/cron.ts", "computeNextCronAtMsResult", "both"],
  ["src/workflow/cron.ts", "computeNextCronAtMs", "signal"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.reconcileOrphanedLiveParentRuns.runWorkflowTransactionForStoreHost.<callback@3>",
    "signal",
  ],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.transitionRun", "signal"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.recordWorkflowRequestTerminal.runWorkflowTransactionForStoreHost.<callback@3>",
    "signal",
  ],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.getWorkflowRequestDispatchHandoff.runWorkflowTransactionForStoreHost.<callback@3>",
    "signal",
  ],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.transitionOperation", "signal"],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.transitionWait", "signal"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.createTriggerInvocation.runWorkflowTransactionForStoreHost.<callback@3>",
    "signal",
  ],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.transitionTrigger", "signal"],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.fireClaimedTrigger", "signal"],
  ["src/workflow/workflow-definition-store.ts", "captureWorkflowDefinitionStoreOperation", "both"],
  [
    "src/workflow/workflow-definition-store.ts",
    "adaptWorkflowDefinitionStoreResultToHost",
    "signal",
  ],
  ["src/workflow/workflow-definition-store.ts", "lstatOrNull", "both"],
  ["src/workflow/workflow-definition-store.ts", "ensureDirectoryWithoutSymlinks", "signal"],
  ["src/workflow/workflow-definition-store.ts", "assertDirectorySegmentsWithoutSymlinks", "signal"],
  ["src/workflow/workflow-definition-store.ts", "canonicalDirectory", "signal"],
  ["src/workflow/workflow-definition-store.ts", "readBoundedRegularFile", "signal"],
  [
    "src/workflow/workflow-definition-store.ts",
    "WorkflowDefinitionStore.createResult.captureWorkflowDefinitionStoreOperation.<callback@2>",
    "signal",
  ],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.definitionPath", "signal"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.getUnchecked", "signal"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.saveUnchecked", "both"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.listUnchecked", "signal"],
  [
    "src/workflow/workflow-definition-store.ts",
    "WorkflowDefinitionStore.createSnapshotUnchecked",
    "both",
  ],
  [
    "src/workflow/workflow-definition-store.ts",
    "WorkflowDefinitionStore.readSnapshotUnchecked",
    "signal",
  ],
  ["src/workflow/workflow-definition.ts", "propertyName", "signal"],
  ["src/workflow/workflow-definition.ts", "literalValue", "signal"],
  ["src/workflow/workflow-definition.ts", "assertNoForbiddenSyntax", "signal"],
  ["src/workflow/workflow-definition.ts", "assertNoForbiddenSyntax.visit", "signal"],
  ["src/workflow/workflow-definition.ts", "assertHelperParameters", "signal"],
  ["src/workflow/workflow-definition.ts", "assertHelperFunction", "signal"],
  [
    "src/workflow/workflow-definition.ts",
    "assertHelperFunction.assertInstrumentableHostCalls",
    "signal",
  ],
  ["src/workflow/workflow-definition.ts", "assertTopLevelHelpers", "both"],
  ["src/workflow/workflow-definition.ts", "assertBindingSafeHostCalls.assertBody.visit", "signal"],
  ["src/workflow/workflow-definition.ts", "assertBindingSafeHostCalls", "signal"],
  [
    "src/workflow/workflow-definition.ts",
    "assertBindingSafeHostCalls.assertDirectReference",
    "signal",
  ],
  [
    "src/workflow/workflow-definition.ts",
    "assertStaticHostCallArguments.assertStaticObject",
    "both",
  ],
  ["src/workflow/workflow-definition.ts", "assertStaticHostCallArguments.visit", "signal"],
  ["src/workflow/workflow-definition.ts", "extractDefinitionObject", "signal"],
  ["src/workflow/workflow-definition.ts", "extractStaticMetadata", "signal"],
  ["src/workflow/workflow-definition.ts", "assertNoShadowedWorkflowBindings.visit", "signal"],
  ["src/workflow/workflow-definition.ts", "assertSchemaBounds", "signal"],
  ["src/workflow/workflow-definition.ts", "normalizeInputSchema", "signal"],
  ["src/workflow/workflow-definition.ts", "assertPlainJsonObjects", "signal"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowArgsUnchecked", "signal"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowSourceUnchecked", "signal"],
  ["src/workflow/workflow-definition.ts", "captureWorkflowValidation", "both"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowArgs", "signal"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowSource", "signal"],
  ["src/workflow/workflow-domain.ts", "normalizeWorkflowResourcePolicy", "signal"],
  ["src/workflow/workflow-engine.ts", "adaptWorkflowCallInputToSandboxHost", "signal"],
  ["src/workflow/workflow-engine.ts", "adaptWorkflowSandboxResultToEngineHost", "signal"],
  ["src/workflow/workflow-engine.ts", "cancelWorkflowSandboxForEngineHost", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.stop", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.claimAndLaunch", "capture"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.loadSnapshot", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.createSandbox", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.assertPersistedIntegrity", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.runSandbox", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.handleCall", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.waitDurably", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.completeStructuralOperation", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.dispatchAgent", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.dispatchAgent.adoptReceipt", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.dispatchAgentSafely", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.adoptTerminalReceipt", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.stopAgentRequests", "signal"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.finishRun", "signal"],
  ["src/workflow/workflow-live-parent-bridge.ts", "toCompletionIdentity", "signal"],
  ["src/workflow/workflow-live-parent-bridge.ts", "toCompletion", "signal"],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.registerParent.listPending",
    "signal",
  ],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.registerParent.listPendingSettledAsync.map.<callback@1>",
    "capture",
  ],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.ensureChildActivityForwarding",
    "signal",
  ],
  ["src/workflow/workflow-operation-policy.ts", "resolveWorkflowAgentOperationInput", "signal"],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.ensureInitialCard",
    "signal",
  ],
  ["src/workflow/workflow-progress-projector.ts", "WorkflowProgressProjector.reconcile", "capture"],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.drainActionOutboxProjections",
    "capture",
  ],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.drainPendingActionOutboxProjections",
    "both",
  ],
  ["src/workflow/workflow-progress-projector.ts", "WorkflowProgressProjector.project", "capture"],
  ["src/workflow/workflow-progress-projector.ts", "WorkflowProgressProjector.projectRun", "both"],
  ["src/workflow/workflow-progress-view.ts", "buildWorkflowProgressView", "signal"],
  ["src/workflow/workflow-sandbox-child.js", "<module>", "signal"],
  ["src/workflow/workflow-sandbox.ts", "decodeWorkflowSandboxOutputLine", "both"],
  ["src/workflow/workflow-sandbox.ts", "adaptWorkflowSandboxOutputToProcessHost", "signal"],
  ["src/workflow/workflow-sandbox.ts", "boundedJsonLine", "signal"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox", "both"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.performTermination", "both"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.cancel.<callback>", "both"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.respondToHostCall", "both"],
  ["src/workflow/workflow-source-compiler.ts", "parseWorkflowCallSiteManifestUnchecked", "both"],
  ["src/workflow/workflow-source-compiler.ts", "parseWorkflowCallSiteManifestResult", "both"],
  ["src/workflow/workflow-source-compiler.ts", "parseWorkflowCallSiteManifest", "signal"],
  ["src/workflow/workflow-source-compiler.ts", "compileWorkflowSourceUnchecked", "signal"],
  ["src/workflow/workflow-source-compiler.ts", "compileWorkflowSourceResult", "both"],
  ["src/workflow/workflow-source-compiler.ts", "compileWorkflowSource", "signal"],
  ["src/workflow/workflow-subagent-dispatcher.ts", "completionStatus", "signal"],
  [
    "src/workflow/workflow-subagent-dispatcher.ts",
    "WorkflowSubagentDispatcher.definitions",
    "both",
  ],
  ["src/workflow/workflow-subagent-dispatcher.ts", "WorkflowSubagentDispatcher.delegate", "signal"],
  [
    "src/workflow/workflow-subagent-dispatcher.ts",
    "WorkflowSubagentDispatcher.waitForCompletion",
    "signal",
  ],
  ["src/workflow/workflow-trigger-scheduler.ts", "WorkflowTriggerScheduler.tick", "capture"],
  ["src/workflow/workflow-trigger-scheduler.ts", "WorkflowTriggerScheduler.fire", "capture"],
  ["src/conversation/thread-embedding.ts", "createConversationThreadEmbeddingAdapter", "signal"],
  ["src/conversation/thread-service.ts", "adaptModelResolutionToGenerationHost", "signal"],
  ["src/ssh/remote-js/remote-runner-entry.ts", "opApplyPatch", "signal"],
  ["src/surface/bridge/bus-agent-runner.ts", "adaptModelResolutionToBusRunnerHost", "signal"],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>.materializeClaude",
    "signal",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>.serverCompaction",
    "signal",
  ],
  ["src/surface/discord/discord-request-router/common.ts", "withDefaultToolsConfig", "signal"],
  ["src/tool-server/tools/onboarding.ts", "requireWorkspaceRoot", "signal"],
  ["src/tools/apply-patch/apply-patch-core.ts", "parsePatch", "signal"],
  ["src/tools/batch.ts", "collectApplyPatchTouchedPaths", "signal"],
  ["src/tools/batch.ts", "collectEditFileTouchedPaths", "signal"],
  ["src/tools/batch.ts", "batchTool", "signal"],
  ["src/mcp/registry.ts", "McpRegistry.discoverTools.map.<callback@1>", "signal"],
  ["src/surface/bridge/bus-agent-runner.ts", "startBusAgentRunner.then.<callback@1>", "signal"],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "resolveAnthropicFallbackDownload.promise.<callback>",
    "signal",
  ],
  ["src/surface/bridge/bus-agent-runner/stats.ts", "getToolDefsText.map.<callback@1>", "capture"],
  [
    "src/tool-server/tools/surface.ts",
    "inferAttachmentMimeType.basenameFromUrl.<callback>",
    "capture",
  ],
  [
    "src/transcript/transcript-store.ts",
    "SqliteTranscriptStore.migrate.transaction.<callback@1>",
    "signal",
  ],
  [
    "src/transcript/transcript-store.ts",
    "SqliteTranscriptStore.migrate.transaction.<callback@1>.map.<callback@1>",
    "signal",
  ],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.enableOrphanHandling.setTimeout.<callback@1>",
    "capture",
  ],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.registerParent.map.<callback@1>",
    "signal",
  ],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.requestProjection.setTimeout.<callback@1>",
    "capture",
  ],
  [
    "src/workflow/workflow-sandbox.ts",
    "startWorkflowSandbox.executionResult.<callback>.stderrPromise.<callback>",
    "signal",
  ],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.executionResult.<callback>", "both"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.result.<callback>", "both"],
] as const;
