export type PreciseExceptionIdentity = readonly [
  module: string,
  exportName: string,
  mode: "capture" | "signal" | "both",
];

export const CORE_REVIEWED_PANIC_IDENTITIES = [
  ["src/surface/adapter.ts", "preserveSurfacePanic"],
  ["src/github/webhook/github-webhook-server.ts", "superviseGithubWebhookHandler"],
  ["src/runtime/create-core-runtime.ts", "startCoreMcpServices.catch.<callback@1>"],
  [
    "src/surface/bridge/bus-agent-runner/output-publisher.ts",
    "createAgentOutputPublisher.enqueue.superviseSettlement",
  ],
  ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.emit.catch.<callback@1>"],
  ["src/workflow/workflow-engine.ts", "WorkflowEngine.claimAndLaunch.catch.<callback@1>"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.respondToHostCall"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.result.<callback>"],
] as const;

export const CORE_FATAL_SIGNAL_IDENTITIES = [
  [
    "src/surface/discord/discord-adapter.ts",
    "DiscordAdapter.reportDetachedPanic.queueMicrotask.<callback@1>",
  ],
] as const;

export const PRECISE_EXCEPTION_IDENTITIES: Readonly<
  Record<string, readonly PreciseExceptionIdentity[]>
> = {
  "apps/acp-controller": [
    ["external-adapters.ts", "captureAcpFailure", "capture"],
    ["external-adapters.ts", "signalAcpDefect", "signal"],
    [
      "acp-harness-client.ts",
      "AcpHarnessClient.connect.captureExternal.<callback@2>@2.start",
      "both",
    ],
  ],
  "apps/core": [
    ["src/surface/bridge/bridge-log.ts", "formatBridgeTaggedErrorForLog", "capture"],
    [
      "src/conversation/thread-service.ts",
      "captureConversationThreadSqliteOperation.catch",
      "capture",
    ],
    ["src/conversation/thread-service.ts", "parseConversationThreadJson.catch", "capture"],
    ["src/workflow/workflow-error-log.ts", "formatWorkflowErrorForLog", "capture"],
    [
      "src/conversation/thread-materializer-worker.ts",
      "startConversationThreadMaterializer.postRequest.catch",
      "capture",
    ],
    ["src/transcript/transcript-persistence-codec.ts", "decodeSerialized.catch", "capture"],
    [
      "src/transcript/transcript-store.ts",
      "SqliteTranscriptStore.emitPersistenceDiagnosticsAfterTransaction.catch",
      "capture",
    ],
    ["src/conversation/thread-summarization-worker.ts", "runJob", "signal"],
    [
      "src/conversation/thread-summarization-worker.ts",
      "captureThreadSummarizationWorkerOperationFailure",
      "capture",
    ],
    [
      "src/conversation/thread-summarization-worker.ts",
      "captureThreadSummarizationWorkerCleanupFailure",
      "capture",
    ],
    ["src/conversation/thread-worker.ts", "rethrowConversationThreadWorkerPanic", "signal"],
    [
      "src/conversation/thread-worker.ts",
      "startConversationThreadSummarizationWorker.postRequest",
      "capture",
    ],
    ["src/conversation/thread-worker.ts", "startConversationThreadWorker.tick", "capture"],
    ["src/custom-commands/manager.ts", "importCustomCommandModule", "both"],
    ["src/custom-commands/manager.ts", "invokeCustomCommand", "both"],
    ["src/custom-commands/manager.ts", "settleCustomCommand", "both"],
    ["src/github/github-api.ts", "adaptGithubApiResultToHost", "signal"],
    ["src/github/github-api.ts", "captureGithubApiExternal", "both"],
    ["src/github/github-app-token.ts", "captureGithubAppAuth", "both"],
    ["src/github/github-app.ts", "captureGithubAppFs", "both"],
    ["src/github/github-app.ts", "readGithubAppPrivateKeyPem", "signal"],
    ["src/github/github-app.ts", "readGithubAppSecret", "signal"],
    ["src/github/github-auth.ts", "captureGithubAuthExternal", "both"],
    ["src/github/github-auth.ts", "getGithubViewerLoginOrThrow", "signal"],
    ["src/github/github-auth.ts", "getPreferredGithubAuthOrThrow", "signal"],
    ["src/github/github-ids.ts", "parseGithubSessionId", "signal"],
    ["src/github/github-user-token.ts", "captureGithubUserTokenFs", "both"],
    ["src/github/github-user-token.ts", "readGithubUserTokenSecret", "signal"],
    ["src/github/github-user-token.ts", "writeGithubUserTokenSecret", "signal"],
    ["src/github/webhook/github-webhook-server.ts", "captureGithubWebhookOperation", "both"],
    ["src/plugins/builtin/local-tools.ts", "captureLocalApplyPatchFs", "both"],
    ["src/plugins/builtin/local-tools.ts", "signalBuiltinToolHostError", "signal"],
    ["src/plugins/builtin/server-tools.ts", "signalBuiltinPluginSkip", "signal"],
    ["src/plugins/manager.ts", "createCoreToolPluginManager.adaptPluginResultToHost", "signal"],
    ["src/runtime/core-config-watch.ts", "captureCoreConfigWatchRead", "both"],
    ["src/runtime/create-core-runtime.ts", "adaptCoreEventBusCleanupResultToHost", "signal"],
    ["src/runtime/create-core-runtime.ts", "adaptCoreEventBusSetupResultToStartup", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "adaptCustomCommandInitializationResultToStartup",
      "signal",
    ],
    ["src/runtime/create-core-runtime.ts", "captureCoreEventBusCleanup", "both"],
    ["src/runtime/create-core-runtime.ts", "captureCoreLilacBusConstruction", "both"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRawBusConstruction", "both"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRedisConnection", "both"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRedisConstruction", "both"],
    ["src/runtime/create-core-runtime.ts", "captureCoreWorkspacePreparation", "both"],
    ["src/runtime/create-core-runtime.ts", "createCoreEventBusFatalReporter.report", "capture"],
    ["src/runtime/create-core-runtime.ts", "createCoreRuntime.probeRedisHealth", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.readCoreConfigParserVersion",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.start.try.captureSummarizationRuntimeOperation",
      "capture",
    ],
    ["src/runtime/create-core-runtime.ts", "createCoreRuntime.startCoreConfigWatcher", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.validateCoreConfigOnChange",
      "signal",
    ],
    ["src/runtime/create-core-runtime.ts", "createCoreRuntimeCleanupSupervisor.finish", "signal"],
    ["src/runtime/create-core-runtime.ts", "createCoreRuntimeCleanupSupervisor.run", "capture"],
    ["src/runtime/error-format.ts", "projectRuntimeError", "capture"],
    ["src/runtime/main.ts", "catch", "capture"],
    ["src/runtime/main.ts", "handleProcessSignal.catch", "capture"],
    ["src/runtime/process-handlers.ts", "createProcessHandlers.handleFatal", "capture"],
    ["src/runtime/process-handlers.ts", "createProcessHandlers.superviseFatal.catch", "capture"],
    ["src/shared/event-bus-result.ts", "adaptEventPublishResultToHost", "signal"],
    ["src/surface/bridge/subscribe-from-bus.ts", "rethrowBusToAdapterPanic", "signal"],
    ["src/surface/github/github-adapter.ts", "GithubAdapter.readMsg.catch.<callback@1>@1", "both"],
    ["src/surface/github/github-adapter.ts", "GithubAdapter.readMsg.catch.<callback@1>@2", "both"],
    ["src/surface/github/github-adapter.ts", "GithubAdapter.sendMsg", "capture"],
    [
      "src/surface/store/discord-search-store.ts",
      "DiscordSearchService.maybeHealChannel",
      "capture",
    ],
    ["src/tool-server/tools/web-search/shared.ts", "throwIfAborted", "signal"],
    ["src/tool-server/tools/web.ts", "checkSignal", "signal"],
    ["src/tools/tool-result-adapters.ts", "adaptToolResultToHost", "signal"],
    [
      "src/transcript/transcript-store.ts",
      "SqliteTranscriptStore.migrate.transaction.<callback@1>",
      "signal",
    ],
    [
      "src/transcript/transcript-store.ts",
      "SqliteTranscriptStore.migrate.transaction.<callback@1>.map.<callback@1>",
      "signal",
    ],
    [
      "src/conversation/thread-worker.ts",
      "signalConversationThreadWorkerPanicToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/github/github-app-token.ts", "getGithubInstallationTokenOrThrow", "signal"],
    ["src/github/webhook/github-webhook-server.ts", "superviseGithubWebhookHandler", "both"],
    ["src/mcp/config.ts", "serializeMcpConfigYaml", "signal"],
    ["src/mcp/catalog-identity.ts", "parseCatalogToolStableId", "capture"],
    ["src/mcp/config.ts", "parseMcpConfigYaml", "capture"],
    ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFile", "signal"],
    ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFileResult", "both"],
    ["src/mcp/credential-file.ts", "resolveMcpOAuthCredentialPath", "signal"],
    ["src/mcp/credential-file.ts", "updateMcpOAuthCredentialFile", "signal"],
    ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomic", "signal"],
    ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomicResult.finish", "signal"],
    ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomicResult", "capture"],
    [
      "src/mcp/credential-file.ts",
      "updateMcpOAuthCredentialFileResult.then.<callback@1>@1",
      "both",
    ],
    [
      "src/mcp/credential-file.ts",
      "updateMcpOAuthCredentialFileResult.then.<callback@2>",
      "capture",
    ],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.redirectToAuthorization",
      "signal",
    ],
    ["src/mcp/oauth-callback.ts", "McpOAuthCallbackService.start", "capture"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.assertActive", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.clientInformation", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.completeAuthorization", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.rejectImplicitAuthorization", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.startAuthorization", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProviderService.startAuthorization", "signal"],
    ["src/mcp/oauth-provider.ts", "captureOAuthAttempt", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.closeClientInBackground.catch.<callback@1>", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.closeEntry", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.closeTransportInBackground.catch.<callback@1>", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.handleTerminalFailure.catch.<callback@1>", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.init.runLifecycle.<callback@1>", "signal"],
    ["src/mcp/registry.ts", "McpRegistry.initializeCandidate", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.reconcileServer", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.shutdown.runLifecycle.<callback@1>", "signal"],
    ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute", "both"],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.codeVerifier",
      "signal",
    ],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.saveState",
      "signal",
    ],
    ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute.catch.<callback@1>", "both"],
    [
      "src/mcp/registry.ts",
      "McpRegistry.initializeCandidate.withDeadline.<callback@2>.onUncaughtError",
      "capture",
    ],
    ["src/mcp/registry.ts", "McpRegistry.resolveTransport.catch@1", "capture"],
    ["src/mcp/registry.ts", "McpRegistry.resolveTransport.catch@2", "capture"],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.probeRedisHealth.try.<callback>.setTimeout.<callback@1>",
      "signal",
    ],
    ["src/runtime/create-core-runtime.ts", "startCoreMcpServices.catch.<callback@1>", "capture"],
    [
      "src/shared/agent-output-activity.ts",
      "createAgentOutputActivityPublisher.<callback>.catch.<callback@1>",
      "capture",
    ],
    ["src/surface/bridge/subscribe-from-bus.ts", "captureBusToAdapterEffect", "capture"],
    ["src/surface/bridge/subscribe-from-bus.ts", "superviseBusToAdapterCleanup", "both"],
    ["src/surface/bridge/subscribe-from-bus.ts", "adaptBusToAdapterSubscriptionStart", "signal"],
    ["src/surface/bridge/subscribe-from-bus.ts", "adaptBusToAdapterSubscriptionStop", "signal"],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.startSessionQueueDrain.superviseDetachedDrain",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.superviseSubscriptionDone",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.drainSessionQueue.reportAgentActivityError",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/output-publisher.ts",
      "createAgentOutputPublisher.enqueue.superviseSettlement",
      "capture",
    ],
    ["src/surface/bridge/bus-agent-runner.ts", "adaptModelResolutionToBusRunnerHost", "signal"],
    ["src/surface/bridge/bus-agent-runner.ts", "captureBusAgentRunnerOperation", "capture"],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "maybeBuildAutoInjectedThreadSearchMessages.publishToolStatusBestEffort",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "maybeBuildAutoInjectedThreadSearchMessages",
      "capture",
    ],
    ["src/surface/bridge/bus-agent-runner.ts", "maybeBuildSkillsSectionForPrimary", "both"],
    ["src/surface/bridge/bus-agent-runner.ts", "projectBusAgentRunnerError", "capture"],
    ["src/surface/bridge/bus-agent-runner.ts", "rethrowBusAgentRunnerPanic", "signal"],
    ["src/surface/bridge/bus-agent-runner.ts", "signalBusAgentRunnerHostFailure", "signal"],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.observeSupervisedSubscriptionDoneRejection",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.startSessionQueueDrain.observeSupervisedDrainRejection",
      "capture",
    ],
    ["src/surface/bridge/bus-agent-runner.ts", "startBusAgentRunner.stopSubscription", "signal"],
    ["src/surface/bridge/bus-agent-runner.ts", "startBusAgentRunner.then.<callback@1>", "signal"],
    ["src/surface/bridge/bus-agent-runner.ts", "startBusAgentRunner", "signal"],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "applyToRunningAgent.promptWhileIdle.catch.<callback@1>",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.handleCmdRequestMessage",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.materializeClaude",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.serverCompaction",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "fitImageForAnthropicFallback.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "fitImageForAnthropicFallback.catch.<callback@1>@2",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "fitImageForAnthropicFallback",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "readAnthropicFallbackCache",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "readAnthropicFallbackCache.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "readAnthropicFallbackCache.catch.<callback@1>@2",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "readAnthropicFallbackCache.catch.<callback@1>@3",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "readAnthropicFallbackCache.catch.<callback@1>@4",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "renderAnthropicFallbackImageCandidate.catch.<callback@1>",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "resolveAnthropicFallbackDownload.promise.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "resolveAnthropicFallbackDownload",
      "signal",
    ],
    ["src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts", "runCommand", "capture"],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "writeAnthropicFallbackCache.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "writeAnthropicFallbackCache.catch.<callback@1>@2",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "writeAnthropicFallbackCache.catch.<callback@1>@3",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "writeAnthropicFallbackCache.catch.<callback@1>@4",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "createCoreNamedClaudeRuntime.createCandidate",
      "both",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "createCoreNamedClaudeRuntime.finalize",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "createCoreNamedClaudeRuntime.materializeAttempt",
      "both",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "createCoreNamedClaudeRuntime.recordSuccessfulModelCall",
      "both",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.createCandidate",
      "both",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.finalize",
      "capture",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.materializeAttempt",
      "both",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.recordSuccessfulModelCall",
      "both",
    ],
    ["src/surface/bridge/bus-agent-runner/formatting.ts", "safeStringify", "capture"],
    [
      "src/surface/bridge/bus-agent-runner/output-publisher.ts",
      "adaptAgentOutputPublishResultToHost",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/prompt-overlays.ts",
      "resolveSessionAdditionalPrompts",
      "both",
    ],
    ["src/surface/bridge/bus-agent-runner/stats.ts", "getToolDefsText.map.<callback@1>", "capture"],
    [
      "src/surface/bridge/bus-agent-runner/tool-failure-logging.ts",
      "toSerializablePreview",
      "capture",
    ],
    ["src/surface/discord/discord-request-router.ts", "adaptRouterConfigResult", "signal"],
    [
      "src/surface/discord/discord-request-router.ts",
      "adaptDiscordRequestRouterStartOutcomeToHost",
      "signal",
    ],
    ["src/surface/discord/discord-request-router.ts", "adaptRouterSubscriptionsStop", "signal"],
    ["src/surface/discord/discord-request-router.ts", "captureRouterActiveBatchGate", "both"],
    ["src/surface/discord/discord-request-router.ts", "captureRouterDebounceFlush", "capture"],
    ["src/surface/discord/discord-request-router.ts", "captureRouterRouting", "both"],
    [
      "src/surface/discord/discord-request-router.ts",
      "signalDiscordRequestRouterPlatformMismatch",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.evaluateAdapterSuppression",
      "both",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.evaluateDirectReplyRouterGate",
      "both",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.reloadCoreConfigIfNeeded",
      "both",
    ],
    ["src/surface/discord/discord-request-router/common.ts", "getDiscordFlags", "both"],
    ["src/surface/discord/discord-request-router/gate.ts", "shouldForwardByGate", "capture"],
    [
      "src/surface/discord/discord-request-router/context.ts",
      "resolvePreviousMessageText.catch.<callback@1>",
      "both",
    ],
    [
      "src/surface/discord/discord-request-router/context.ts",
      "resolveRepliedToMessageText.catch.<callback@1>",
      "both",
    ],
    [
      "src/surface/discord/discord-request-router/publish.ts",
      "publishActiveChannelPrompt.catch.<callback@1>",
      "capture",
    ],
    [
      "src/surface/bridge/discord-search-indexer.ts",
      "startDiscordSearchIndexer.subscribe.<callback@1>.catch.<callback@1>",
      "capture",
    ],
    ["src/surface/bridge/request-composition.ts", "compareDiscordSnowflakeLike", "capture"],
    [
      "src/surface/bridge/request-composition.ts",
      "composeRecentChannelMessages.catch.<callback@1>",
      "capture",
    ],
    ["src/surface/bridge/request-composition.ts", "safeListReactions", "capture"],
    [
      "src/surface/bridge/request-composition/attachments.ts",
      "appendDiscordAttachmentsToUserContent",
      "both",
    ],
    [
      "src/surface/bridge/request-composition/attachments.ts",
      "downloadDiscordAttachment",
      "signal",
    ],
    ["src/surface/bridge/request-composition/attachments.ts", "resolveOwnedFileData", "signal"],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "compareDiscordSnowflakeLike",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "fetchReplyChainFrom.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "fetchReplyChainFrom.catch.<callback@1>@2",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "fetchReplyChainFrom.run.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "fetchReplyChainFrom.run.catch.<callback@1>@2",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "resolveMergeBlockEndingAt.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/surface/bridge/request-composition/reply-chain.ts",
      "resolveMergeBlockEndingAt.catch.<callback@1>@2",
      "capture",
    ],
    ["src/surface/bridge/surface-metadata.ts", "parseSurfaceMetadataLine", "capture"],
    [
      "src/surface/bridge/publish-to-bus.ts",
      "bridgeAdapterToBus.subscribe.<callback@1>",
      "capture",
    ],
    ["src/surface/bridge/publish-to-bus.ts", "bridgeAdapterToBus.subscribe.<callback@1>", "signal"],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.editMsg.catch.<callback@1>@1",
      "both",
    ],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.editMsg.catch.<callback@1>@2",
      "both",
    ],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.fetchDiscordMessage.catch.<callback@1>@1",
      "both",
    ],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.fetchDiscordMessage.catch.<callback@1>@2",
      "both",
    ],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.emit.catch.<callback@1>", "capture"],
    [
      "src/tool-server/create-tool-server.ts",
      "signalFatalToolCallDefectToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/tool-server/create-tool-server.ts", "projectFatalToolCallDefect", "capture"],
    ["src/tool-server/create-tool-server.ts", "adaptPanicToToolServerHost", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptPluginLifecycleResultToHost", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptPluginListResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptSafetyModeResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptToolAuthenticationResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptToolPayloadResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptToolRequestHeadersResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptToolRouteResultToElysia", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptToolServerOptionsResultToHost", "signal"],
    ["src/tool-server/create-tool-server.ts", "frameworkErrorLogProjection", "capture"],
    ["src/tool-server/create-tool-server.ts", "isToolInputValidationCause", "capture"],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.captureActiveLevel1Work",
      "both",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.captureRuntimeDiagnostics",
      "both",
    ],
    ["src/tool-server/health-state.ts", "createToolServerHealthState.getSnapshot", "both"],
    ["src/tool-server/health-state.ts", "previewReason", "capture"],
    [
      "src/tool-server/request-message-cache.ts",
      "adaptRequestMessageCacheStartResultToHost",
      "signal",
    ],
    [
      "src/tool-server/request-message-cache.ts",
      "adaptRequestMessageCacheStopResultToHost",
      "signal",
    ],
    ["src/tool-server/runtime-diagnostics.ts", "readOptional", "capture"],
    ["src/tool-server/tools/attachment.ts", "adaptAttachmentResultToToolHost", "signal"],
    [
      "src/tool-server/tools/attachment.ts",
      "Attachment.callDownload.catch.<callback@1>",
      "capture",
    ],
    ["src/tool-server/tools/codex.ts", "adaptCodexResultToToolHost", "signal"],
    ["src/tool-server/tools/content-inspect.ts", "ContentInspect.inspect", "capture"],
    ["src/tool-server/tools/content-inspect.ts", "adaptContentInspectResultToToolHost", "signal"],
    ["src/tool-server/tools/content-inspect.ts", "decodeInspectText", "capture"],
    ["src/tool-server/tools/content-inspect.ts", "looksLikeUtf8Text", "capture"],
    [
      "src/tool-server/tools/content-inspect.ts",
      "readInspectResponseBytes.catch.<callback@1>",
      "capture",
    ],
    [
      "src/tool-server/tools/conversation-thread.ts",
      "adaptConversationThreadResultToToolHost",
      "signal",
    ],
    ["src/tool-server/tools/generate.ts", "adaptGenerateResultToToolHost", "signal"],
    ["src/tool-server/tools/generate.ts", "writeFileWithUniqueName", "capture"],
    ["src/tool-server/tools/onboarding.ts", "Onboarding.runCallable.runStep", "capture"],
    [
      "src/tool-server/tools/onboarding.ts",
      "Onboarding.runCallable.catch.<callback@1>@1",
      "capture",
    ],
    [
      "src/tool-server/tools/onboarding.ts",
      "Onboarding.runCallable.catch.<callback@1>@2",
      "capture",
    ],
    ["src/tool-server/tools/onboarding.ts", "adaptOnboardingResultToToolHost", "signal"],
    ["src/tool-server/tools/onboarding.ts", "ensureDir0700", "capture"],
    ["src/tool-server/tools/onboarding.ts", "hasAnySkillMdUnder", "capture"],
    ["src/tool-server/tools/onboarding.ts", "isRootUser", "capture"],
    ["src/tool-server/tools/onboarding.ts", "pathExecutable", "capture"],
    [
      "src/tool-server/tools/programmatic-workflow.ts",
      "adaptWorkflowInvocationResultToToolHost",
      "signal",
    ],
    [
      "src/tool-server/tools/programmatic-workflow.ts",
      "ProgrammaticWorkflow.definitions.catch.<callback@1>",
      "capture",
    ],
    ["src/tool-server/tools/programmatic-workflow.ts", "adaptWorkflowToolResultToHost", "signal"],
    [
      "src/tool-server/tools/resolve-discord-session-id.ts",
      "adaptDiscordSessionResolutionResultToToolHost",
      "signal",
    ],
    ["src/tool-server/tools/skills.ts", "adaptSkillsResultToToolHost", "signal"],
    ["src/tool-server/tools/surface.ts", "adaptSurfaceResultToToolHost", "signal"],
    ["src/tool-server/tools/surface.ts", "Surface.callActivitiesRecentAgentWrites", "capture"],
    ["src/tool-server/tools/surface.ts", "Surface.linkSentMessageToTranscript", "capture"],
    [
      "src/tool-server/tools/surface.ts",
      "resolveDiscordReferencedMessage.catch.<callback@1>",
      "capture",
    ],
    ["src/tool-server/tools/surface.ts", "resolveGuildIdForChannel", "capture"],
    ["src/tool-server/tools/web.ts", "adaptWebResultToToolHost", "signal"],
    ["src/tool-server/tools/web.ts", "Web.callFetch", "capture"],
    ["src/tool-server/tools/web.ts", "Web.callSearch", "capture"],
    ["src/tool-server/tools/web.ts", "Web.extractPageContent", "capture"],
    ["src/tool-server/tools/web.ts", "Web.extractPageContentWithProvider", "capture"],
    ["src/tool-server/tools/web.ts", "Web.pathExecutable", "capture"],
    ["src/tool-server/tools/web.ts", "Web.refreshWebConfig", "capture"],
    ["src/tool-server/tools/web.ts", "Web.renderPageContent.catch.<callback@1>", "capture"],
    ["src/tool-server/tools/web.ts", "Web.renderPageContent.onAbort.catch.<callback@1>", "capture"],
    ["src/tool-server/tools/web.ts", "readResponseTextWithLimit.catch.<callback@1>", "capture"],
    [
      "src/tool-server/tools/web.ts",
      "readResponseTextWithLimit.onAbort.catch.<callback@1>",
      "capture",
    ],
    [
      "src/tool-server/tools/web-search/exa-web-search-provider.ts",
      "adaptExaProviderResultToHost",
      "signal",
    ],
    [
      "src/tool-server/tools/web-search/firecrawl-web-search-provider.ts",
      "adaptFirecrawlSearchResultToProviderHost",
      "signal",
    ],
    [
      "src/tool-server/tools/web-search/tavily-web-search-provider.ts",
      "adaptTavilyProviderResultToHost",
      "signal",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.reportWatchdogDefect",
      "capture",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.signalWatchdogDefect.queueMicrotask.<callback@1>",
      "signal",
    ],
    [
      "src/tool-server/tools/codex.ts",
      "Codex.runCallable.runPendingTransition.<callback@1>@1.then.<callback@2>",
      "capture",
    ],
    ["src/tool-server/tools/onboarding.ts", "scheduleRestart.setTimeout.<callback@1>", "capture"],
    [
      "src/tool-server/tools/surface.ts",
      "Surface.callMessagesSearch.map.<callback@1>@3",
      "capture",
    ],
    ["src/tool-server/tools/web-search/shared.ts", "withAbortSignal.<callback>.onAbort", "signal"],
    [
      "src/tool-server/tools/web-search/shared.ts",
      "withAbortSignal.<callback>.then.<callback@2>",
      "capture",
    ],
    ["src/tool-server/tools/web.ts", "withAbortSignal.<callback>.onAbort", "signal"],
    ["src/tool-server/tools/web.ts", "withAbortSignal.<callback>.then.<callback@2>", "capture"],
    ["src/tools/bash-impl.ts", "settleBashExecution.then.<callback@2>", "capture"],
    ["src/tools/bash-impl.ts", "cleanupBashSpills.then.<callback@2>", "capture"],
    ["src/tools/bash-output-sanitizer.ts", "settleBashOutputCleanup.then.<callback@2>", "capture"],
    ["src/workflow/workflow-engine.ts", "WorkflowEngine.claimAndLaunch.catch.<callback@1>", "both"],
    ["src/workflow/workflow-engine.ts", "WorkflowEngine.waitForAgentRequest", "signal"],
    [
      "src/workflow/workflow-live-parent-bridge.ts",
      "WorkflowLiveParentBridge.registerParent.listPending.map.<callback@1>",
      "signal",
    ],
    ["src/workflow/workflow-sandbox-child.js", "send", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "jsonClone", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "parseCallSiteManifest", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "decodeInputMessage", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "hostCall", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "lockDownPrimordials", "capture"],
    ["src/workflow/workflow-sandbox-child.js", "lockDownPrimordials.value", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "start", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "handle.catch.<callback@1>", "capture"],
    [
      "src/workflow/workflow-sandbox.ts",
      "startWorkflowSandbox.executionResult.<callback>.then.<callback@2>",
      "capture",
    ],
    ["src/workflow/workflow-trigger-scheduler.ts", "WorkflowTriggerScheduler.tick", "signal"],
  ],
  "apps/mini-lilac": [
    ["build.ts", "captureBuildOperation", "both"],
    ["build.ts", "signalBuildFailure", "signal"],
    ["install-local.ts", "captureInstallOperation", "both"],
    ["install-local.ts", "signalLocalInstallFailure", "signal"],
    ["src/main.ts", "captureCommand", "both"],
  ],
  "apps/mini-lilac-server": [
    ["src/main.ts", "acquireDatabaseLock", "signal"],
    ["src/main.ts", "adaptLifecycleResultToHost", "signal"],
    ["src/main.ts", "captureNodeCliParsing", "both"],
    ["src/main.ts", "captureServerCleanup", "both"],
    ["src/main.ts", "captureServerOperation", "both"],
    ["src/main.ts", "rethrowPanic", "signal"],
    ["src/main.ts", "settleCleanupEffect", "capture"],
    ["src/main.ts", "settleCleanupResult", "capture"],
    ["src/main.ts", "settleLifecycleResult", "capture"],
    ["src/main.ts", "settleShutdownEffect", "capture"],
    ["src/main.ts", "shutdownMiniLilacServer", "signal"],
    ["src/server.ts", "adaptMiniLilacPersistenceResultToHost", "signal"],
    ["src/server.ts", "canonicalDirectory", "both"],
    ["src/server.ts", "captureHttpOperation", "capture"],
    ["src/server.ts", "classifyHttpOperationFailure", "signal"],
    ["src/server.ts", "enqueueSseKeepAlive", "both"],
    ["src/server.ts", "signalMiniLilacServerConfigurationFailure", "signal"],
    ["src/server.ts", "signalMiniLilacServerPanicToProcess.queueMicrotask.<callback@1>", "signal"],
    ["src/main.ts", "shutdownMiniLilacServerResult.settleLifecycleResult.<callback@2>", "signal"],
    ["src/server.ts", "pumpSseBody.<callback>", "both"],
  ],
  "apps/mini-lilac-tui": [
    ["src/failure-adapter.ts", "captureTuiFailure", "capture"],
    ["src/failure-adapter.ts", "signalTuiDefect", "signal"],
  ],
  "apps/tool-bridge": [
    ["client.ts", "captureBridgeFailure", "capture"],
    ["client.ts", "signalBridgeDefect", "signal"],
  ],
  "packages/agent": [
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.runTurn", "capture"],
    [
      "agent-run-idle-watchdog.ts",
      "createAgentRunIdleWatchdog.renewTimeoutPromise.then.<callback@2>",
      "capture",
    ],
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.executeExternalToolCall.map.<callback@1>", "signal"],
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.executeExpansionChildren.normalizeEntries", "capture"],
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.finishIdleRecovery", "both"],
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.invokeSteeringDeliveryHook", "capture"],
    ["ai-sdk-pi-agent.ts", "AiSdkPiAgent.runLoop.<callback>", "both"],
    ["ai-sdk-pi-agent.ts", "cloneSteeringValue", "capture"],
    ["ai-sdk-pi-agent.ts", "recoveryToolOutput", "capture"],
    ["ai-sdk-pi-agent.ts", "signalAgentStateHost", "signal"],
    ["ai-sdk-pi-agent.ts", "signalExternalToolCallHost", "signal"],
    ["atomic-tool-execution.ts", "cleanupFailedAtomicToolCall", "capture"],
    ["atomic-tool-execution.ts", "consumeAtomicToolResultStream", "capture"],
    ["atomic-tool-execution.ts", "executeAtomicToolCallResult", "capture"],
    ["atomic-tool-execution.ts", "isJsonToolOutputValueInner", "capture"],
    ["atomic-tool-execution.ts", "normalizeToolResultOutput", "capture"],
    ["atomic-tool-execution.ts", "settleAtomicToolCallImpl", "capture"],
    ["atomic-tool-execution.ts", "settleAtomicToolCallResult", "capture"],
    ["atomic-tool-execution.ts", "signalAtomicToolExecutionHost", "signal"],
    ["atomic-tool-execution.ts", "stringifyToolInput", "capture"],
    ["atomic-tool-execution.ts", "toJsonToolOutputValue", "capture"],
    ["atomic-tool-execution.ts", "validateInput", "capture"],
    ["auto-compaction.ts", "attachAutoCompaction.canonicalModelCallPreflight", "both"],
    ["auto-compaction.ts", "compactRepairedMessages", "capture"],
    ["auto-compaction.ts", "resolveContextLimit", "capture"],
    ["auto-compaction.ts", "signalAutoCompactionHost", "signal"],
    ["auto-compaction.ts", "stringifyTextOnly", "capture"],
    ["auto-compaction.ts", "stringifyUnknown", "capture"],
    ["auto-compaction.ts", "summarizeMessagesHierarchicalResult", "capture"],
    ["failure-adapters.ts", "rethrowAgentPanic", "signal"],
    ["openai-server-compaction.ts", "compactWithOpenAIResponses", "signal"],
    ["openai-server-compaction.ts", "compactWithOpenAIResponsesResult", "capture"],
    ["retry-backoff.ts", "createRetryBackoffBudget.next", "capture"],
    ["session-continuation.ts", "fileStringContentDigest", "capture"],
    ["session-continuation.ts", "sanitizeReplayValue", "capture"],
    ["session-continuation.ts", "signalCanonicalJsonInvalid", "signal"],
    ["session-continuation.ts", "toolInputText", "capture"],
    ["transient-model-retry.ts", "createTransientModelRetryController.handler", "both"],
    ["transient-model-retry.ts", "defaultErrorSummary", "capture"],
  ],
  "packages/bash-safety": [
    ["src/analyze/analyze-command.ts", "parseBashCommand.catch", "both"],
    ["src/rules-rm.ts", "resolveRmPaths.catch", "both"],
  ],
  "packages/claude-code-bridge": [
    ["claude-attempt-runtime-owner.ts", "ClaudeAttemptRuntimeOwner.prepare", "signal"],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.adaptRunEndRetirementToHost",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.getNativeInputEstimateFloor",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.recordSuccessfulModelCall",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.retireForCanonicalReplacement",
      "signal",
    ],
    ["claude-attempt-runtime-owner.ts", "ClaudeAttemptRuntimeOwner.retireForRetry", "signal"],
    ["claude-attempt-runtime-owner.ts", "captureCandidateFactory", "both"],
    ["claude-code-run.ts", "captureClaudeContextUsage", "both"],
    ["claude-code-run.ts", "captureCleanupOperationSync", "both"],
    ["claude-code-run.ts", "captureExternalOperation", "both"],
    ["claude-code-run.ts", "captureExternalOperationSync", "both"],
    ["claude-code-run.ts", "materializeClaudeCodeRun", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult", "both"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.clear", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.clearResult", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.createUtilityModel", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.drainQueryControllers", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.finalizeToHost", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.spawnTrackedProcess", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.waitForObservability", "signal"],
    ["claude-code-run.ts", "settleQueryAndProcess", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.disposeResult.<callback>", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.dispose.<callback>", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.finalizeResult.<callback>", "signal"],
    [
      "claude-code-tools.ts",
      "createClaudeCodeToolBridgeResult.setRequestHandler.<callback@2>@2",
      "both",
    ],
    ["claude-code-tools.ts", "createClaudeCodeToolBridge", "signal"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult", "both"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult.close", "signal"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult.closeResult", "both"],
    ["claude-code-tools.ts", "mapToolResultOutputToMcp", "signal"],
    ["claude-code-tools.ts", "stringifyJson", "both"],
    ["claude-code-tools.ts", "validateClaudeCodeBuiltInTools", "signal"],
  ],
  "packages/coding-tools": [
    ["src/bash.ts", "bashFailureMessage", "capture"],
    ["src/bash.ts", "executeLocalBash", "capture"],
    ["src/bash.ts", "captureBashPromise.then.<callback@2>", "capture"],
    ["src/bash.ts", "createBashSpool.activate", "both"],
    ["src/bash.ts", "createBashSpool.close", "signal"],
    ["src/bash.ts", "createBashSpool.write.then.<callback@1>", "both"],
    ["src/bash.ts", "captureStreamingBash.then.<callback@2>", "capture"],
    ["src/bash.ts", "ignoreBashFailure", "both"],
    ["src/bash.ts", "killProcessGroup", "both"],
    ["src/batch.ts", "resolveBatchEditTargets", "signal"],
    ["src/batch.ts", "validateInput", "signal"],
    ["src/batch.ts", "projectBatchExternalCause", "capture"],
    ["src/batch.ts", "captureBatchExternal", "capture"],
    ["src/batch.ts", "captureBatchExternal.then.<callback@2>", "capture"],
    ["src/buffered-file-sink.ts", "BufferedFileSink.open", "both"],
    ["src/buffered-file-sink.ts", "continueBufferedSinkQueue", "both"],
    ["src/host-compatibility.ts", "adaptCodingToolResultToHost", "signal"],
  ],
  "packages/event-bus": [
    ["event-dead-letter.ts", "checkedDeadLetterAcceptance", "signal"],
    ["lilac-bus.ts", "checkedDisposition", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.close", "both"],
    ["lilac-bus.ts", "createLilacBus.bus.getTopicWatermark", "both"],
    ["lilac-bus.ts", "createLilacBus.bus.publish", "both"],
    ["lilac-bus.ts", "createLilacBus.bus.retireTopicConsumerGroup", "both"],
    ["lilac-bus.ts", "createLilacBus.bus.trimTopicBeforeCheckpoint", "both"],
    ["redis-connection-pool.ts", "RedisConnectionPool.createConnection", "both"],
    ["redis-streams-bus.ts", "deliveryAction", "signal"],
    ["redis-streams-bus.ts", "ensureGroup", "both"],
    ["redis-streams-bus.ts", "RedisStreamsBus.captureAcknowledgedTrim", "capture"],
    ["redis-streams-bus.ts", "RedisStreamsBus.close", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.fetch", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.flushPendingTrims", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.publish", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.retireConsumerGroup", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.catch.<callback@1>@1", "capture"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.catch.<callback@1>@2", "capture"],
    ["redis-streams-bus.ts", "RedisStreamsBus.trimAcknowledgedPrefix", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.trimBeforeCheckpoint", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.watermark", "signal"],
    [
      "redis-event-dead-letter.ts",
      "RedisEventDeadLetter.accept.captureDeadLetterAcceptance.<callback@1>",
      "signal",
    ],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.cleanupLease.<callback>", "capture"],
  ],
  "packages/fs": [
    ["src/filesystem-operation.ts", "captureFilesystemOperation", "both"],
    ["src/filesystem-operation.ts", "captureFilesystemOperationSync", "both"],
    ["src/fs-impl.ts", "compileEditRegex", "both"],
    ["src/remote-runner-protocol.ts", "decodeJson", "both"],
    ["src/ripgrep.ts", "decodeRipgrepMatchLine", "both"],
    ["src/ripgrep.ts", "ripgrep", "both"],
    ["src/search-backend.ts", "captureFffOperation", "both"],
    ["src/search-backend.ts", "captureFffSyncOperation", "both"],
  ],
  "packages/mini-lilac-client": [
    ["mini-lilac-transport.ts", "captureMiniLilacPromiseOutcome", "capture"],
    ["mini-lilac-transport.ts", "captureMiniLilacStreamRead", "capture"],
    ["mini-lilac-transport.ts", "captureMiniLilacSyncOutcome", "capture"],
    ["mini-lilac-transport.ts", "parseMiniLilacStream.pull", "both"],
    ["mini-lilac-transport.ts", "parseMiniLilacStream.transform", "signal"],
    ["mini-lilac-transport.ts", "resultToMiniLilacCompatibilityFailure", "signal"],
    ["mini-lilac-transport.ts", "throwMiniLilacPanic", "signal"],
  ],
  "packages/mini-lilac-runtime": [
    [
      "src/session-service.ts",
      "signalMiniLilacRuntimePanicToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/workspace-history-store.ts", "superviseOutcome.rejection.reject", "signal"],
    ["src/workspace-history-store.ts", "throwFailure", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.constructor", "signal"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.captureResult",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.invalidateCaptureCacheResult",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.prepareRestore",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.resumePreparedRestore",
      "signal",
    ],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.withWorkspaceLockResult", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.resumeLocked", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.publicResult", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.publicWorkspaceResult", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.validateSourceGitDirectory", "both"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.runGit", "both"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.runPrivateGitToHandle", "both"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.emitMetric.run.<callback@2>.catch.<callback@1>",
      "capture",
    ],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.withWorkspaceLock", "signal"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.capture",
      "signal",
    ],
    ["src/config.ts", "captureRuntimeConfigRead", "capture"],
    ["src/config.ts", "captureRuntimeConfigYaml", "capture"],
    ["src/config.ts", "loadRuntimeConfig", "signal"],
    ["src/config.ts", "throwRuntimeConfigPanic", "signal"],
    ["src/model-catalog.ts", "captureModelCatalogPromise", "capture"],
    ["src/model-catalog.ts", "captureModelCatalogSync", "capture"],
    ["src/model-catalog.ts", "ModelCatalog.constructor", "signal"],
    ["src/model-catalog.ts", "ModelCatalog.get", "signal"],
    ["src/model-catalog.ts", "parseModelRef", "signal"],
    ["src/model-catalog.ts", "resolveLanguageModel", "signal"],
    ["src/model-catalog.ts", "throwModelCatalogPanic", "signal"],
    ["src/providers.ts", "captureProviderPromise", "capture"],
    ["src/providers.ts", "captureProviderSync", "capture"],
    ["src/providers.ts", "createAiProviderRegistry", "signal"],
    ["src/providers.ts", "loadProviderAuth", "signal"],
    ["src/providers.ts", "loadProviderConfig", "signal"],
    ["src/providers.ts", "loadProviderRegistry", "signal"],
    ["src/providers.ts", "throwProviderPanic", "signal"],
    ["src/providers.ts", "writeProviderAuth", "signal"],
    ["src/session-service.ts", "rethrowSessionPanic", "signal"],
    ["src/session-service.ts", "serializedUtf8Bytes", "capture"],
    ["src/session-service.ts", "SessionActor.broadcastCompaction", "capture"],
    ["src/session-service.ts", "SessionActor.closeSubscribers", "capture"],
    ["src/session-service.ts", "SessionActor.commitSteeringBoundary", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.commitSteeringBoundary.withWorkspaceLock.<callback@1>.map.<callback@1>@1",
      "signal",
    ],
    ["src/session-service.ts", "SessionActor.createAgent", "both"],
    ["src/session-service.ts", "SessionActor.createAgent.createCandidate", "both"],
    ["src/session-service.ts", "SessionActor.createAgent.execute", "signal"],
    ["src/session-service.ts", "SessionActor.createAgent.materializeAttempt", "both"],
    ["src/session-service.ts", "SessionActor.createAgent.materializeAttempt.execute", "signal"],
    ["src/session-service.ts", "SessionActor.delegate", "both"],
    ["src/session-service.ts", "SessionActor.delegate.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionActor.enqueueEvent.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionActor.executeTopLevelRun", "both"],
    ["src/session-service.ts", "SessionActor.executeTopLevelRun.then.<callback@2>", "capture"],
    ["src/session-service.ts", "SessionActor.finalizeTopLevelRun", "capture"],
    ["src/session-service.ts", "SessionActor.generateSessionTitle", "both"],
    [
      "src/session-service.ts",
      "SessionActor.generateSessionTitle.withLock.<callback@1>.catch.<callback@1>",
      "capture",
    ],
    ["src/session-service.ts", "SessionActor.publishStoredChunk", "capture"],
    [
      "src/session-service.ts",
      "SessionActor.queueAutomaticCompaction.catch.<callback@1>",
      "capture",
    ],
    ["src/session-service.ts", "SessionActor.queueControlChunks.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionActor.queueSteeringChunk.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionActor.queueSubagentStatus.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionActor.replaceTodos.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.replaceTodos.withLock.<callback@1>.then.<callback@1>@1",
      "signal",
    ],
    [
      "src/session-service.ts",
      "SessionActor.replaceTodos.withLock.<callback@1>.then.<callback@2>",
      "capture",
    ],
    ["src/session-service.ts", "SessionActor.runCompaction", "capture"],
    ["src/session-service.ts", "SessionActor.summarizeForCompaction", "capture"],
    ["src/session-service.ts", "sessionResultToCompatibility", "signal"],
    ["src/session-service.ts", "SessionService.capturePersistencePromise", "capture"],
    ["src/session-service.ts", "SessionService.capturePersistenceResult", "capture"],
    ["src/session-service.ts", "SessionService.constructor", "signal"],
    ["src/session-service.ts", "SessionService.constructor.<callback>@2", "signal"],
    ["src/session-service.ts", "SessionService.constructor.<callback>@3", "capture"],
    ["src/session-service.ts", "SessionService.constructor.catch.<callback@1>", "capture"],
    ["src/session-service.ts", "SessionService.createSessionInternalResult", "capture"],
    ["src/session-service.ts", "SessionService.listSkillsResult", "capture"],
    ["src/session-service.ts", "SessionService.trackOperation.then.<callback@2>", "capture"],
    ["src/session-service.ts", "SessionService.trackTask.then.<callback@2>", "capture"],
    ["src/session-service.ts", "toolOutputErrorText", "capture"],
    ["src/skills.ts", "captureSkillPromise", "capture"],
    ["src/skills.ts", "captureSkillSync", "capture"],
    ["src/skills.ts", "MiniLilacSkillCatalogSnapshot.load", "signal"],
    ["src/skills.ts", "throwSkillPanic", "signal"],
    ["src/sqlite-persistence-codec.ts", "decodePlainJson", "both"],
    ["src/sqlite-persistence-codec.ts", "decodeSuperJson", "both"],
    ["src/sqlite-store.ts", "canonicalCommandPayloadResult", "both"],
    ["src/sqlite-store.ts", "canonicalizeStoredCwd", "capture"],
    ["src/sqlite-store.ts", "captureMiniLilacCleanup", "capture"],
    ["src/sqlite-store.ts", "captureMiniLilacCleanup.rethrow", "signal"],
    ["src/sqlite-store.ts", "closeMiniLilacHistoryRecoveryDatabase", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.acquireCloseBlocker", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.admitRootPromptHistory", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertConservativeProviderTransition", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertHeadsEqualState", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertStateConnectedToRoot", "signal"],
    [
      "src/sqlite-store.ts",
      "MiniLilacSqliteStore.assertWorkspaceHistoryAvailableForOwner",
      "signal",
    ],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.close", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.closeAfterInitializationFailure", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitEmptyHistoryNavigation", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitHistoryCompaction", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitSteeringHistoryBoundary", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.constructor", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.decodeTranscriptNodeValue", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.deleteHistoryOperationRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.deletePendingRunFinalizationRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.getIncomingHistoryTransition", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.initializeSchemaResult", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.insertHistoryTransitionRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.internSerializedChain", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.moveHistoryCursor", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.parseHistoryNavigationResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.requireQuiescentHistorySession", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.reserveHistoryOperation", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.reservePendingRunFinalization", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.restoreSchemaMigrationPragmas", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.runHistoryReadResult", "both"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.saveHistoryCommandResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.validateHistoryTransitionDestination", "signal"],
    ["src/sqlite-store.ts", "readMiniLilacHistoryRecoveryStatusResult", "both"],
    ["src/sqlite-store.ts", "reportMiniLilacCleanupFailure", "capture"],
    ["src/sqlite-store.ts", "serializeStoreValueResult", "both"],
    ["src/sqlite-store.ts", "storeResultToLegacy", "signal"],
    ["src/sqlite-store.ts", "throwPrimaryAfterCleanup", "signal"],
    ["src/sqlite-todo-persistence-codec.ts", "decodeMiniLilacTodos", "both"],
    ["src/sqlite-todo-persistence-codec.ts", "readMiniLilacTodos", "both"],
    ["src/webfetch.ts", "captureWebfetchPromise", "capture"],
    ["src/webfetch.ts", "captureWebfetchSync", "capture"],
    ["src/webfetch.ts", "throwWebfetchPanic", "signal"],
    ["src/webfetch.ts", "webfetchResultToLegacyOutput", "signal"],
    ["src/workspace-history-persistence-codec.ts", "parseJson", "capture"],
    ["src/session-service.ts", "SessionActor.startPrompt.withLock.<callback@1>", "both"],
    [
      "src/session-service.ts",
      "SessionActor.startPrompt.withLock.<callback@1>.withWorkspaceLock.<callback@1>",
      "both",
    ],
    [
      "src/session-service.ts",
      "SessionActor.commitSteeringBoundary.withWorkspaceLock.<callback@1>",
      "both",
    ],
    [
      "src/session-service.ts",
      "SessionActor.commitSteeringBoundary.withWorkspaceLock.<callback@1>.committed.<callback>",
      "both",
    ],
    [
      "src/session-service.ts",
      "SessionActor.commitRunFinalization.withWorkspaceLock.<callback@1>",
      "both",
    ],
    ["src/session-service.ts", "SessionActor.steer.withLock.<callback@1>", "signal"],
    ["src/session-service.ts", "SessionActor.cancel.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.navigateHistory.withWorkspaceLock.<callback@1>",
      "both",
    ],
    ["src/session-service.ts", "SessionActor.compact.withLock.<callback@1>", "signal"],
    ["src/session-service.ts", "SessionActor.updateBindings.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionService.promptDelegatedSession.withDelegatedSessionLock.<callback@2>",
      "both",
    ],
    ["src/webfetch.ts", "inspectHtml.captureWebfetchSync.<callback@1>.onopentag", "signal"],
  ],
  "packages/remote-fs-runner": [
    ["src/cli.ts", "captureRuntimeOperation", "capture"],
    ["src/cli.ts", "captureStartupLockOperation", "capture"],
    ["src/cli.ts", "executeDaemonRequest", "capture"],
    ["src/cli.ts", "opaqueErrorCause", "capture"],
    ["src/cli.ts", "opaqueErrorMessage", "capture"],
    ["src/cli.ts", "preservePanic", "signal"],
    ["src/cli.ts", "readStdinText", "capture"],
    ["src/cli.ts", "releaseStartupLock", "capture"],
    ["src/cli.ts", "reportCleanupFailureWithoutMaskingOperation", "capture"],
    ["src/cli.ts", "reportMainFailure", "capture"],
    ["src/cli.ts", "runWithStartupLockCleanup", "signal"],
    ["src/cli.ts", "spawnDaemon", "capture"],
    ["src/cli.ts", "superviseStartupLockCleanupAfterOperationDefect", "capture"],
  ],
  "packages/plugin-runtime": [
    ["capabilities.ts", "capturePluginInspection", "both"],
    ["capabilities.ts", "isPluginPanic", "capture"],
    ["capabilities.ts", "opaquePluginExceptionMessage", "capture"],
    ["capabilities.ts", "safePluginExceptionCause", "capture"],
    ["discovery.ts", "captureFileOperation", "both"],
    ["discovery.ts", "decodePluginFilesystemErrorCode", "capture"],
    ["discovery.ts", "decodePluginPackageJsonText", "both"],
    ["hooks.ts", "captureAsyncHook", "both"],
    ["hooks.ts", "captureSyncHook", "both"],
    ["loader.ts", "loadToolPluginModuleCapability", "both"],
    ["manager.ts", "ToolPluginManager.finishCleanup", "signal"],
    ["manager.ts", "ToolPluginManager.registerPluginPreservingPanic", "signal"],
    ["manager.ts", "captureManagerHook", "both"],
  ],
  "packages/tool-results": [
    ["src/tool-result-artifact-store.ts", "adaptToolResultArtifactReadToAvailability", "signal"],
    [
      "src/tool-result-artifact-store.ts",
      "adaptToolResultArtifactReadToUnavailablePolicy",
      "signal",
    ],
    ["src/tool-result-artifact-store.ts", "captureToolResultEffect.then.<callback@2>", "capture"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.readEncryptedWindow.<callback>",
      "both",
    ],
    ["src/tool-result-artifact-store.ts", "adaptToolResultArtifactStoreInitToHost", "signal"],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.captureOperation", "both"],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.decrypt", "both"],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.encrypt", "both"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.readEncryptedWindow",
      "both",
    ],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.readMetadata", "both"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.writeEncryptedStreamAtomic",
      "both",
    ],
    ["src/tool-result-output-normalizer.ts", "serializeOutput", "both"],
  ],
  "packages/utils": [
    ["agent-prompts.ts", "exists", "both"],
    ["agent-prompts.ts", "loadPromptTemplateState", "both"],
    ["agent-prompts.ts", "parsePromptTemplateState", "both"],
    ["agent-prompts.ts", "promptWorkspaceSignature", "both"],
    ["agent-prompts.ts", "readTextIfExists", "both"],
    ["ai-error.ts", "parseResponseBody", "capture"],
    ["ai-error.ts", "extractAiErrorLogDetails", "capture"],
    ["ai-error.ts", "sanitizeRequestUrl", "capture"],
    ["build-info.ts", "getBuildInfoFileCacheKey", "both"],
    ["build-info.ts", "readBuildInfoFile", "both"],
    ["build-info.ts", "readGitBuildInfo", "both"],
    ["codex-oauth.ts", "readCodexTokens", "signal"],
    ["codex-oauth.ts", "clearCodexTokens", "signal"],
    ["codex-oauth.ts", "clearCodexTokensResult", "both"],
    ["codex-oauth.ts", "decodeCodexTokens", "both"],
    ["codex-oauth.ts", "exchangeCodeForTokens", "signal"],
    ["codex-oauth.ts", "exchangeCodeForTokensResult", "both"],
    ["codex-oauth.ts", "parseCodexOAuthCallback", "both"],
    ["codex-oauth.ts", "parseJwtClaims", "both"],
    ["codex-oauth.ts", "readCodexTokensResult", "both"],
    ["codex-oauth.ts", "refreshAccessToken", "signal"],
    ["codex-oauth.ts", "refreshAccessTokenResult", "both"],
    ["codex-oauth.ts", "startCodexOAuthLogin.catch.<callback@1>", "both"],
    ["codex-oauth.ts", "startCodexOAuthLogin.exchange", "signal"],
    ["codex-oauth.ts", "startCodexOAuthLogin.runExchangeResult", "both"],
    ["codex-oauth.ts", "startCodexOAuthLogin", "both"],
    ["codex-oauth.ts", "writeCodexTokens", "signal"],
    ["codex-oauth.ts", "writeSecretFileResult", "both"],
    ["core-config.ts", "decodeCoreConfigYaml", "both"],
    ["core-config.ts", "getCoreConfig", "both"],
    ["core-config.ts", "parseCoreConfig", "signal"],
    ["core-config.ts", "readCoreConfigVersion", "signal"],
    ["core-config.ts", "resolveDiscordToken", "signal"],
    ["core-config/v1.ts", "parseCoreConfigV1ToUniversal", "signal"],
    ["core-config/v2.ts", "parseCoreConfigV2ToUniversal", "signal"],
    ["custom-commands.ts", "decodeCustomCommandResult", "both"],
    ["custom-commands.ts", "discoverCustomCommands", "both"],
    ["custom-commands.ts", "pathExists", "both"],
    ["custom-commands.ts", "readCustomCommandDefinition", "both"],
    ["find-root.ts", "findWorkspaceRoot", "signal"],
    ["find-root.ts", "hasWorkspacesFieldResult", "both"],
    ["friendly-units.ts", "parseFriendlyByteSize", "signal"],
    ["friendly-units.ts", "parseFriendlyDurationMs", "signal"],
    ["llm-wire-debug.ts", "JsonlWriter.append", "both"],
    ["llm-wire-debug.ts", "captureNonStreamingResponse", "both"],
    ["llm-wire-debug.ts", "consumeSseDebugStream", "both"],
    ["llm-wire-debug.ts", "createWriter", "both"],
    ["llm-wire-debug.ts", "decodeRequestBody", "both"],
    ["llm-wire-debug.ts", "safeParseJson", "both"],
    ["llm-wire-debug.ts", "withLlmWireDebugFetch.<callback>", "both"],
    ["logging.ts", "OpenObserveJsonlStream.write", "both"],
    ["logging.ts", "projectOpenObserveRequestFailure", "both"],
    ["logging.ts", "reportOpenObserveDiagnostics", "both"],
    ["logging.ts", "safeJsonStringify", "both"],
    ["logging.ts", "signalOpenObservePanic", "capture"],
    ["logging.ts", "signalOpenObservePanic.queueMicrotask.<callback@1>", "signal"],
    ["model-capability.ts", "ModelCapability.loadRegistryResult.<callback>", "both"],
    ["model-capability.ts", "ModelCapability.resolve", "signal"],
    ["model-capability.ts", "parseModelSpecifier", "signal"],
    ["model-provider.ts", "createCodexOAuthProvider.<callback>", "signal"],
    [
      "model-provider.ts",
      "createCodexOAuthProvider.<callback>.refreshIfNeeded.<callback>",
      "signal",
    ],
    ["model-provider.ts", "decodeCodexResponsesRequestBody", "both"],
    ["model-provider.ts", "normalizeCodexResponsesRequestRecord", "signal"],
    ["model-slot.ts", "fromDurableResolvedModelPlan", "signal"],
    ["model-slot.ts", "fromDurableResolvedModelRequest", "signal"],
    ["model-slot.ts", "resolveModelChain", "signal"],
    ["model-slot.ts", "resolveModelPlan", "signal"],
    ["model-slot.ts", "resolveModelRef", "signal"],
    ["model-slot.ts", "resolveModelSlot", "signal"],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.connectWebSocket.<callback>",
      "capture",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.connectWebSocket.<callback>.onError",
      "capture",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onMessage.<callback>",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.closeSocket",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.enqueueNormalizedEvent",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onAbort",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onClose",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start",
      "capture",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch",
      "both",
    ],
    ["openai-responses-websocket-fetch.ts", "decodeRequestBody", "capture"],
    ["openai-responses-websocket-fetch.ts", "decodeResponsesRequestBody", "both"],
    ["openai-responses-websocket-fetch.ts", "normalizeSseFrame", "capture"],
    ["openai-responses-websocket-fetch.ts", "signalResponsesStreamError", "signal"],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onMessage.catch.<callback@1>",
      "both",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "maybeNormalizeResponsesSseResponse.start.<callback>",
      "capture",
    ],
    ["persistence.ts", "runBunSqliteTransaction", "both"],
    ["persistence.ts", "runBunSqliteTransaction.transaction.<callback@1>", "signal"],
    ["runtime-utils.ts", "isPanic", "capture"],
    ["runtime-utils.ts", "opaqueErrorCause", "capture"],
    ["runtime-utils.ts", "opaqueErrorMessage", "capture"],
    ["server-compaction-request.ts", "prepareServerCompactionRequestResult", "both"],
    ["server-compaction-request.ts", "withServerCompactionRequestFetch.wrappedFetch", "signal"],
    ["skills.ts", "parseSkillMarkdown", "signal"],
    ["skills.ts", "parseSkillMarkdownResult", "both"],
    ["skills.ts", "pathExists", "both"],
    ["skills.ts", "readTextPrefixResult", "both"],
    ["skills.ts", "scanSkillPathsBounded", "both"],
    ["tool-call-input-normalization.ts", "parsePlainObjectJson", "capture"],
  ],
};
