export const ARCHITECTURE_FINDINGS_EXIT_CODE = 42;
export const ARCHITECTURE_WORKSPACE_FIXTURE_ENV = "LILAC_ARCHITECTURE_WORKSPACE_FIXTURE";
export const ARCHITECTURE_WORKSPACE_FIXTURE_VALUE = "stage8-integration";
